// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for GSL
class flutter_gsl {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  flutter_gsl(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  flutter_gsl.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_FINE_STRUCTURE =
      _lookup<ffi.Double>('GSL_CONST_NUM_FINE_STRUCTURE');

  double get GSL_CONST_NUM_FINE_STRUCTURE =>
      _GSL_CONST_NUM_FINE_STRUCTURE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_AVOGADRO =
      _lookup<ffi.Double>('GSL_CONST_NUM_AVOGADRO');

  double get GSL_CONST_NUM_AVOGADRO => _GSL_CONST_NUM_AVOGADRO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_YOTTA =
      _lookup<ffi.Double>('GSL_CONST_NUM_YOTTA');

  double get GSL_CONST_NUM_YOTTA => _GSL_CONST_NUM_YOTTA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_ZETTA =
      _lookup<ffi.Double>('GSL_CONST_NUM_ZETTA');

  double get GSL_CONST_NUM_ZETTA => _GSL_CONST_NUM_ZETTA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_EXA =
      _lookup<ffi.Double>('GSL_CONST_NUM_EXA');

  double get GSL_CONST_NUM_EXA => _GSL_CONST_NUM_EXA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_PETA =
      _lookup<ffi.Double>('GSL_CONST_NUM_PETA');

  double get GSL_CONST_NUM_PETA => _GSL_CONST_NUM_PETA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_TERA =
      _lookup<ffi.Double>('GSL_CONST_NUM_TERA');

  double get GSL_CONST_NUM_TERA => _GSL_CONST_NUM_TERA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_GIGA =
      _lookup<ffi.Double>('GSL_CONST_NUM_GIGA');

  double get GSL_CONST_NUM_GIGA => _GSL_CONST_NUM_GIGA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_MEGA =
      _lookup<ffi.Double>('GSL_CONST_NUM_MEGA');

  double get GSL_CONST_NUM_MEGA => _GSL_CONST_NUM_MEGA.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_KILO =
      _lookup<ffi.Double>('GSL_CONST_NUM_KILO');

  double get GSL_CONST_NUM_KILO => _GSL_CONST_NUM_KILO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_MILLI =
      _lookup<ffi.Double>('GSL_CONST_NUM_MILLI');

  double get GSL_CONST_NUM_MILLI => _GSL_CONST_NUM_MILLI.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_MICRO =
      _lookup<ffi.Double>('GSL_CONST_NUM_MICRO');

  double get GSL_CONST_NUM_MICRO => _GSL_CONST_NUM_MICRO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_NANO =
      _lookup<ffi.Double>('GSL_CONST_NUM_NANO');

  double get GSL_CONST_NUM_NANO => _GSL_CONST_NUM_NANO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_PICO =
      _lookup<ffi.Double>('GSL_CONST_NUM_PICO');

  double get GSL_CONST_NUM_PICO => _GSL_CONST_NUM_PICO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_FEMTO =
      _lookup<ffi.Double>('GSL_CONST_NUM_FEMTO');

  double get GSL_CONST_NUM_FEMTO => _GSL_CONST_NUM_FEMTO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_ATTO =
      _lookup<ffi.Double>('GSL_CONST_NUM_ATTO');

  double get GSL_CONST_NUM_ATTO => _GSL_CONST_NUM_ATTO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_ZEPTO =
      _lookup<ffi.Double>('GSL_CONST_NUM_ZEPTO');

  double get GSL_CONST_NUM_ZEPTO => _GSL_CONST_NUM_ZEPTO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_NUM_YOCTO =
      _lookup<ffi.Double>('GSL_CONST_NUM_YOCTO');

  double get GSL_CONST_NUM_YOCTO => _GSL_CONST_NUM_YOCTO.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_SPEED_OF_LIGHT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_SPEED_OF_LIGHT');

  double get GSL_CONST_MKSA_SPEED_OF_LIGHT =>
      _GSL_CONST_MKSA_SPEED_OF_LIGHT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT');

  double get GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT =>
      _GSL_CONST_MKSA_GRAVITATIONAL_CONSTANT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PLANCKS_CONSTANT_H =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PLANCKS_CONSTANT_H');

  double get GSL_CONST_MKSA_PLANCKS_CONSTANT_H =>
      _GSL_CONST_MKSA_PLANCKS_CONSTANT_H.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR');

  double get GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR =>
      _GSL_CONST_MKSA_PLANCKS_CONSTANT_HBAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BOLTZMANN =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BOLTZMANN');

  double get GSL_CONST_MKSA_BOLTZMANN => _GSL_CONST_MKSA_BOLTZMANN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT');

  double get GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT =>
      _GSL_CONST_MKSA_STEFAN_BOLTZMANN_CONSTANT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_THOMSON_CROSS_SECTION =
      _lookup<ffi.Double>('GSL_CONST_MKSA_THOMSON_CROSS_SECTION');

  double get GSL_CONST_MKSA_THOMSON_CROSS_SECTION =>
      _GSL_CONST_MKSA_THOMSON_CROSS_SECTION.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ACRE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ACRE');

  double get GSL_CONST_MKSA_ACRE => _GSL_CONST_MKSA_ACRE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ANGSTROM =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ANGSTROM');

  double get GSL_CONST_MKSA_ANGSTROM => _GSL_CONST_MKSA_ANGSTROM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ASTRONOMICAL_UNIT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ASTRONOMICAL_UNIT');

  double get GSL_CONST_MKSA_ASTRONOMICAL_UNIT =>
      _GSL_CONST_MKSA_ASTRONOMICAL_UNIT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BAR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BAR');

  double get GSL_CONST_MKSA_BAR => _GSL_CONST_MKSA_BAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BARN =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BARN');

  double get GSL_CONST_MKSA_BARN => _GSL_CONST_MKSA_BARN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BOHR_MAGNETON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BOHR_MAGNETON');

  double get GSL_CONST_MKSA_BOHR_MAGNETON =>
      _GSL_CONST_MKSA_BOHR_MAGNETON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BOHR_RADIUS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BOHR_RADIUS');

  double get GSL_CONST_MKSA_BOHR_RADIUS => _GSL_CONST_MKSA_BOHR_RADIUS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_BTU =
      _lookup<ffi.Double>('GSL_CONST_MKSA_BTU');

  double get GSL_CONST_MKSA_BTU => _GSL_CONST_MKSA_BTU.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_CALORIE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_CALORIE');

  double get GSL_CONST_MKSA_CALORIE => _GSL_CONST_MKSA_CALORIE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_CANADIAN_GALLON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_CANADIAN_GALLON');

  double get GSL_CONST_MKSA_CANADIAN_GALLON =>
      _GSL_CONST_MKSA_CANADIAN_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_CARAT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_CARAT');

  double get GSL_CONST_MKSA_CARAT => _GSL_CONST_MKSA_CARAT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_CURIE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_CURIE');

  double get GSL_CONST_MKSA_CURIE => _GSL_CONST_MKSA_CURIE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_DAY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_DAY');

  double get GSL_CONST_MKSA_DAY => _GSL_CONST_MKSA_DAY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_DEBYE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_DEBYE');

  double get GSL_CONST_MKSA_DEBYE => _GSL_CONST_MKSA_DEBYE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_DYNE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_DYNE');

  double get GSL_CONST_MKSA_DYNE => _GSL_CONST_MKSA_DYNE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ELECTRON_CHARGE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ELECTRON_CHARGE');

  double get GSL_CONST_MKSA_ELECTRON_CHARGE =>
      _GSL_CONST_MKSA_ELECTRON_CHARGE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT');

  double get GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT =>
      _GSL_CONST_MKSA_ELECTRON_MAGNETIC_MOMENT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ELECTRON_VOLT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ELECTRON_VOLT');

  double get GSL_CONST_MKSA_ELECTRON_VOLT =>
      _GSL_CONST_MKSA_ELECTRON_VOLT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ERG =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ERG');

  double get GSL_CONST_MKSA_ERG => _GSL_CONST_MKSA_ERG.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_FARADAY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_FARADAY');

  double get GSL_CONST_MKSA_FARADAY => _GSL_CONST_MKSA_FARADAY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_FATHOM =
      _lookup<ffi.Double>('GSL_CONST_MKSA_FATHOM');

  double get GSL_CONST_MKSA_FATHOM => _GSL_CONST_MKSA_FATHOM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_FOOT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_FOOT');

  double get GSL_CONST_MKSA_FOOT => _GSL_CONST_MKSA_FOOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_FOOTCANDLE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_FOOTCANDLE');

  double get GSL_CONST_MKSA_FOOTCANDLE => _GSL_CONST_MKSA_FOOTCANDLE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_FOOTLAMBERT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_FOOTLAMBERT');

  double get GSL_CONST_MKSA_FOOTLAMBERT => _GSL_CONST_MKSA_FOOTLAMBERT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_GAUSS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_GAUSS');

  double get GSL_CONST_MKSA_GAUSS => _GSL_CONST_MKSA_GAUSS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_GRAM_FORCE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_GRAM_FORCE');

  double get GSL_CONST_MKSA_GRAM_FORCE => _GSL_CONST_MKSA_GRAM_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_GRAV_ACCEL =
      _lookup<ffi.Double>('GSL_CONST_MKSA_GRAV_ACCEL');

  double get GSL_CONST_MKSA_GRAV_ACCEL => _GSL_CONST_MKSA_GRAV_ACCEL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_HECTARE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_HECTARE');

  double get GSL_CONST_MKSA_HECTARE => _GSL_CONST_MKSA_HECTARE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_HORSEPOWER =
      _lookup<ffi.Double>('GSL_CONST_MKSA_HORSEPOWER');

  double get GSL_CONST_MKSA_HORSEPOWER => _GSL_CONST_MKSA_HORSEPOWER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_HOUR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_HOUR');

  double get GSL_CONST_MKSA_HOUR => _GSL_CONST_MKSA_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_INCH =
      _lookup<ffi.Double>('GSL_CONST_MKSA_INCH');

  double get GSL_CONST_MKSA_INCH => _GSL_CONST_MKSA_INCH.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_INCH_OF_MERCURY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_INCH_OF_MERCURY');

  double get GSL_CONST_MKSA_INCH_OF_MERCURY =>
      _GSL_CONST_MKSA_INCH_OF_MERCURY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_INCH_OF_WATER =
      _lookup<ffi.Double>('GSL_CONST_MKSA_INCH_OF_WATER');

  double get GSL_CONST_MKSA_INCH_OF_WATER =>
      _GSL_CONST_MKSA_INCH_OF_WATER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_JOULE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_JOULE');

  double get GSL_CONST_MKSA_JOULE => _GSL_CONST_MKSA_JOULE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_KILOMETERS_PER_HOUR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_KILOMETERS_PER_HOUR');

  double get GSL_CONST_MKSA_KILOMETERS_PER_HOUR =>
      _GSL_CONST_MKSA_KILOMETERS_PER_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_KILOPOUND_FORCE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_KILOPOUND_FORCE');

  double get GSL_CONST_MKSA_KILOPOUND_FORCE =>
      _GSL_CONST_MKSA_KILOPOUND_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_KNOT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_KNOT');

  double get GSL_CONST_MKSA_KNOT => _GSL_CONST_MKSA_KNOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_LAMBERT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_LAMBERT');

  double get GSL_CONST_MKSA_LAMBERT => _GSL_CONST_MKSA_LAMBERT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_LIGHT_YEAR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_LIGHT_YEAR');

  double get GSL_CONST_MKSA_LIGHT_YEAR => _GSL_CONST_MKSA_LIGHT_YEAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_LITER =
      _lookup<ffi.Double>('GSL_CONST_MKSA_LITER');

  double get GSL_CONST_MKSA_LITER => _GSL_CONST_MKSA_LITER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_LUMEN =
      _lookup<ffi.Double>('GSL_CONST_MKSA_LUMEN');

  double get GSL_CONST_MKSA_LUMEN => _GSL_CONST_MKSA_LUMEN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_LUX =
      _lookup<ffi.Double>('GSL_CONST_MKSA_LUX');

  double get GSL_CONST_MKSA_LUX => _GSL_CONST_MKSA_LUX.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MASS_ELECTRON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MASS_ELECTRON');

  double get GSL_CONST_MKSA_MASS_ELECTRON =>
      _GSL_CONST_MKSA_MASS_ELECTRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MASS_MUON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MASS_MUON');

  double get GSL_CONST_MKSA_MASS_MUON => _GSL_CONST_MKSA_MASS_MUON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MASS_NEUTRON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MASS_NEUTRON');

  double get GSL_CONST_MKSA_MASS_NEUTRON => _GSL_CONST_MKSA_MASS_NEUTRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MASS_PROTON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MASS_PROTON');

  double get GSL_CONST_MKSA_MASS_PROTON => _GSL_CONST_MKSA_MASS_PROTON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_METER_OF_MERCURY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_METER_OF_MERCURY');

  double get GSL_CONST_MKSA_METER_OF_MERCURY =>
      _GSL_CONST_MKSA_METER_OF_MERCURY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_METRIC_TON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_METRIC_TON');

  double get GSL_CONST_MKSA_METRIC_TON => _GSL_CONST_MKSA_METRIC_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MICRON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MICRON');

  double get GSL_CONST_MKSA_MICRON => _GSL_CONST_MKSA_MICRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MIL =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MIL');

  double get GSL_CONST_MKSA_MIL => _GSL_CONST_MKSA_MIL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MILE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MILE');

  double get GSL_CONST_MKSA_MILE => _GSL_CONST_MKSA_MILE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MILES_PER_HOUR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MILES_PER_HOUR');

  double get GSL_CONST_MKSA_MILES_PER_HOUR =>
      _GSL_CONST_MKSA_MILES_PER_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MINUTE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MINUTE');

  double get GSL_CONST_MKSA_MINUTE => _GSL_CONST_MKSA_MINUTE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_MOLAR_GAS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_MOLAR_GAS');

  double get GSL_CONST_MKSA_MOLAR_GAS => _GSL_CONST_MKSA_MOLAR_GAS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_NAUTICAL_MILE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_NAUTICAL_MILE');

  double get GSL_CONST_MKSA_NAUTICAL_MILE =>
      _GSL_CONST_MKSA_NAUTICAL_MILE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_NEWTON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_NEWTON');

  double get GSL_CONST_MKSA_NEWTON => _GSL_CONST_MKSA_NEWTON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_NUCLEAR_MAGNETON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_NUCLEAR_MAGNETON');

  double get GSL_CONST_MKSA_NUCLEAR_MAGNETON =>
      _GSL_CONST_MKSA_NUCLEAR_MAGNETON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_OUNCE_MASS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_OUNCE_MASS');

  double get GSL_CONST_MKSA_OUNCE_MASS => _GSL_CONST_MKSA_OUNCE_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PARSEC =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PARSEC');

  double get GSL_CONST_MKSA_PARSEC => _GSL_CONST_MKSA_PARSEC.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PHOT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PHOT');

  double get GSL_CONST_MKSA_PHOT => _GSL_CONST_MKSA_PHOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PINT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PINT');

  double get GSL_CONST_MKSA_PINT => _GSL_CONST_MKSA_PINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_POINT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_POINT');

  double get GSL_CONST_MKSA_POINT => _GSL_CONST_MKSA_POINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_POISE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_POISE');

  double get GSL_CONST_MKSA_POISE => _GSL_CONST_MKSA_POISE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_POUND_FORCE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_POUND_FORCE');

  double get GSL_CONST_MKSA_POUND_FORCE => _GSL_CONST_MKSA_POUND_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_POUND_MASS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_POUND_MASS');

  double get GSL_CONST_MKSA_POUND_MASS => _GSL_CONST_MKSA_POUND_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_POUNDAL =
      _lookup<ffi.Double>('GSL_CONST_MKSA_POUNDAL');

  double get GSL_CONST_MKSA_POUNDAL => _GSL_CONST_MKSA_POUNDAL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT');

  double get GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT =>
      _GSL_CONST_MKSA_PROTON_MAGNETIC_MOMENT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_PSI =
      _lookup<ffi.Double>('GSL_CONST_MKSA_PSI');

  double get GSL_CONST_MKSA_PSI => _GSL_CONST_MKSA_PSI.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_QUART =
      _lookup<ffi.Double>('GSL_CONST_MKSA_QUART');

  double get GSL_CONST_MKSA_QUART => _GSL_CONST_MKSA_QUART.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_RAD =
      _lookup<ffi.Double>('GSL_CONST_MKSA_RAD');

  double get GSL_CONST_MKSA_RAD => _GSL_CONST_MKSA_RAD.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_ROENTGEN =
      _lookup<ffi.Double>('GSL_CONST_MKSA_ROENTGEN');

  double get GSL_CONST_MKSA_ROENTGEN => _GSL_CONST_MKSA_ROENTGEN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_RYDBERG =
      _lookup<ffi.Double>('GSL_CONST_MKSA_RYDBERG');

  double get GSL_CONST_MKSA_RYDBERG => _GSL_CONST_MKSA_RYDBERG.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_SOLAR_MASS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_SOLAR_MASS');

  double get GSL_CONST_MKSA_SOLAR_MASS => _GSL_CONST_MKSA_SOLAR_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_STANDARD_GAS_VOLUME =
      _lookup<ffi.Double>('GSL_CONST_MKSA_STANDARD_GAS_VOLUME');

  double get GSL_CONST_MKSA_STANDARD_GAS_VOLUME =>
      _GSL_CONST_MKSA_STANDARD_GAS_VOLUME.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_STD_ATMOSPHERE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_STD_ATMOSPHERE');

  double get GSL_CONST_MKSA_STD_ATMOSPHERE =>
      _GSL_CONST_MKSA_STD_ATMOSPHERE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_STILB =
      _lookup<ffi.Double>('GSL_CONST_MKSA_STILB');

  double get GSL_CONST_MKSA_STILB => _GSL_CONST_MKSA_STILB.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_STOKES =
      _lookup<ffi.Double>('GSL_CONST_MKSA_STOKES');

  double get GSL_CONST_MKSA_STOKES => _GSL_CONST_MKSA_STOKES.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_TEXPOINT =
      _lookup<ffi.Double>('GSL_CONST_MKSA_TEXPOINT');

  double get GSL_CONST_MKSA_TEXPOINT => _GSL_CONST_MKSA_TEXPOINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_THERM =
      _lookup<ffi.Double>('GSL_CONST_MKSA_THERM');

  double get GSL_CONST_MKSA_THERM => _GSL_CONST_MKSA_THERM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_TON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_TON');

  double get GSL_CONST_MKSA_TON => _GSL_CONST_MKSA_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_TORR =
      _lookup<ffi.Double>('GSL_CONST_MKSA_TORR');

  double get GSL_CONST_MKSA_TORR => _GSL_CONST_MKSA_TORR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_TROY_OUNCE =
      _lookup<ffi.Double>('GSL_CONST_MKSA_TROY_OUNCE');

  double get GSL_CONST_MKSA_TROY_OUNCE => _GSL_CONST_MKSA_TROY_OUNCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_UK_GALLON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_UK_GALLON');

  double get GSL_CONST_MKSA_UK_GALLON => _GSL_CONST_MKSA_UK_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_UK_TON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_UK_TON');

  double get GSL_CONST_MKSA_UK_TON => _GSL_CONST_MKSA_UK_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS =
      _lookup<ffi.Double>('GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS');

  double get GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS =>
      _GSL_CONST_MKSA_UNIFIED_ATOMIC_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_US_GALLON =
      _lookup<ffi.Double>('GSL_CONST_MKSA_US_GALLON');

  double get GSL_CONST_MKSA_US_GALLON => _GSL_CONST_MKSA_US_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_VACUUM_PERMEABILITY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_VACUUM_PERMEABILITY');

  double get GSL_CONST_MKSA_VACUUM_PERMEABILITY =>
      _GSL_CONST_MKSA_VACUUM_PERMEABILITY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_VACUUM_PERMITTIVITY =
      _lookup<ffi.Double>('GSL_CONST_MKSA_VACUUM_PERMITTIVITY');

  double get GSL_CONST_MKSA_VACUUM_PERMITTIVITY =>
      _GSL_CONST_MKSA_VACUUM_PERMITTIVITY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_WEEK =
      _lookup<ffi.Double>('GSL_CONST_MKSA_WEEK');

  double get GSL_CONST_MKSA_WEEK => _GSL_CONST_MKSA_WEEK.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_MKSA_YARD =
      _lookup<ffi.Double>('GSL_CONST_MKSA_YARD');

  double get GSL_CONST_MKSA_YARD => _GSL_CONST_MKSA_YARD.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_SPEED_OF_LIGHT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_SPEED_OF_LIGHT');

  double get GSL_CONST_CGSM_SPEED_OF_LIGHT =>
      _GSL_CONST_CGSM_SPEED_OF_LIGHT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_GRAVITATIONAL_CONSTANT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_GRAVITATIONAL_CONSTANT');

  double get GSL_CONST_CGSM_GRAVITATIONAL_CONSTANT =>
      _GSL_CONST_CGSM_GRAVITATIONAL_CONSTANT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PLANCKS_CONSTANT_H =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PLANCKS_CONSTANT_H');

  double get GSL_CONST_CGSM_PLANCKS_CONSTANT_H =>
      _GSL_CONST_CGSM_PLANCKS_CONSTANT_H.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PLANCKS_CONSTANT_HBAR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PLANCKS_CONSTANT_HBAR');

  double get GSL_CONST_CGSM_PLANCKS_CONSTANT_HBAR =>
      _GSL_CONST_CGSM_PLANCKS_CONSTANT_HBAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BOLTZMANN =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BOLTZMANN');

  double get GSL_CONST_CGSM_BOLTZMANN => _GSL_CONST_CGSM_BOLTZMANN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_STEFAN_BOLTZMANN_CONSTANT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_STEFAN_BOLTZMANN_CONSTANT');

  double get GSL_CONST_CGSM_STEFAN_BOLTZMANN_CONSTANT =>
      _GSL_CONST_CGSM_STEFAN_BOLTZMANN_CONSTANT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_THOMSON_CROSS_SECTION =
      _lookup<ffi.Double>('GSL_CONST_CGSM_THOMSON_CROSS_SECTION');

  double get GSL_CONST_CGSM_THOMSON_CROSS_SECTION =>
      _GSL_CONST_CGSM_THOMSON_CROSS_SECTION.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ASTRONOMICAL_UNIT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ASTRONOMICAL_UNIT');

  double get GSL_CONST_CGSM_ASTRONOMICAL_UNIT =>
      _GSL_CONST_CGSM_ASTRONOMICAL_UNIT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_LIGHT_YEAR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_LIGHT_YEAR');

  double get GSL_CONST_CGSM_LIGHT_YEAR => _GSL_CONST_CGSM_LIGHT_YEAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PARSEC =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PARSEC');

  double get GSL_CONST_CGSM_PARSEC => _GSL_CONST_CGSM_PARSEC.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_GRAV_ACCEL =
      _lookup<ffi.Double>('GSL_CONST_CGSM_GRAV_ACCEL');

  double get GSL_CONST_CGSM_GRAV_ACCEL => _GSL_CONST_CGSM_GRAV_ACCEL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ELECTRON_VOLT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ELECTRON_VOLT');

  double get GSL_CONST_CGSM_ELECTRON_VOLT =>
      _GSL_CONST_CGSM_ELECTRON_VOLT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MASS_ELECTRON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MASS_ELECTRON');

  double get GSL_CONST_CGSM_MASS_ELECTRON =>
      _GSL_CONST_CGSM_MASS_ELECTRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MASS_MUON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MASS_MUON');

  double get GSL_CONST_CGSM_MASS_MUON => _GSL_CONST_CGSM_MASS_MUON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MASS_PROTON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MASS_PROTON');

  double get GSL_CONST_CGSM_MASS_PROTON => _GSL_CONST_CGSM_MASS_PROTON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MASS_NEUTRON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MASS_NEUTRON');

  double get GSL_CONST_CGSM_MASS_NEUTRON => _GSL_CONST_CGSM_MASS_NEUTRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_RYDBERG =
      _lookup<ffi.Double>('GSL_CONST_CGSM_RYDBERG');

  double get GSL_CONST_CGSM_RYDBERG => _GSL_CONST_CGSM_RYDBERG.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MOLAR_GAS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MOLAR_GAS');

  double get GSL_CONST_CGSM_MOLAR_GAS => _GSL_CONST_CGSM_MOLAR_GAS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_STANDARD_GAS_VOLUME =
      _lookup<ffi.Double>('GSL_CONST_CGSM_STANDARD_GAS_VOLUME');

  double get GSL_CONST_CGSM_STANDARD_GAS_VOLUME =>
      _GSL_CONST_CGSM_STANDARD_GAS_VOLUME.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MINUTE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MINUTE');

  double get GSL_CONST_CGSM_MINUTE => _GSL_CONST_CGSM_MINUTE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_HOUR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_HOUR');

  double get GSL_CONST_CGSM_HOUR => _GSL_CONST_CGSM_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_DAY =
      _lookup<ffi.Double>('GSL_CONST_CGSM_DAY');

  double get GSL_CONST_CGSM_DAY => _GSL_CONST_CGSM_DAY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_WEEK =
      _lookup<ffi.Double>('GSL_CONST_CGSM_WEEK');

  double get GSL_CONST_CGSM_WEEK => _GSL_CONST_CGSM_WEEK.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_INCH =
      _lookup<ffi.Double>('GSL_CONST_CGSM_INCH');

  double get GSL_CONST_CGSM_INCH => _GSL_CONST_CGSM_INCH.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FOOT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FOOT');

  double get GSL_CONST_CGSM_FOOT => _GSL_CONST_CGSM_FOOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_YARD =
      _lookup<ffi.Double>('GSL_CONST_CGSM_YARD');

  double get GSL_CONST_CGSM_YARD => _GSL_CONST_CGSM_YARD.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MILE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MILE');

  double get GSL_CONST_CGSM_MILE => _GSL_CONST_CGSM_MILE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_NAUTICAL_MILE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_NAUTICAL_MILE');

  double get GSL_CONST_CGSM_NAUTICAL_MILE =>
      _GSL_CONST_CGSM_NAUTICAL_MILE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FATHOM =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FATHOM');

  double get GSL_CONST_CGSM_FATHOM => _GSL_CONST_CGSM_FATHOM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MIL =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MIL');

  double get GSL_CONST_CGSM_MIL => _GSL_CONST_CGSM_MIL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_POINT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_POINT');

  double get GSL_CONST_CGSM_POINT => _GSL_CONST_CGSM_POINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TEXPOINT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TEXPOINT');

  double get GSL_CONST_CGSM_TEXPOINT => _GSL_CONST_CGSM_TEXPOINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MICRON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MICRON');

  double get GSL_CONST_CGSM_MICRON => _GSL_CONST_CGSM_MICRON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ANGSTROM =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ANGSTROM');

  double get GSL_CONST_CGSM_ANGSTROM => _GSL_CONST_CGSM_ANGSTROM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_HECTARE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_HECTARE');

  double get GSL_CONST_CGSM_HECTARE => _GSL_CONST_CGSM_HECTARE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ACRE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ACRE');

  double get GSL_CONST_CGSM_ACRE => _GSL_CONST_CGSM_ACRE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BARN =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BARN');

  double get GSL_CONST_CGSM_BARN => _GSL_CONST_CGSM_BARN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_LITER =
      _lookup<ffi.Double>('GSL_CONST_CGSM_LITER');

  double get GSL_CONST_CGSM_LITER => _GSL_CONST_CGSM_LITER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_US_GALLON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_US_GALLON');

  double get GSL_CONST_CGSM_US_GALLON => _GSL_CONST_CGSM_US_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_QUART =
      _lookup<ffi.Double>('GSL_CONST_CGSM_QUART');

  double get GSL_CONST_CGSM_QUART => _GSL_CONST_CGSM_QUART.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PINT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PINT');

  double get GSL_CONST_CGSM_PINT => _GSL_CONST_CGSM_PINT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_CUP =
      _lookup<ffi.Double>('GSL_CONST_CGSM_CUP');

  double get GSL_CONST_CGSM_CUP => _GSL_CONST_CGSM_CUP.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FLUID_OUNCE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FLUID_OUNCE');

  double get GSL_CONST_CGSM_FLUID_OUNCE => _GSL_CONST_CGSM_FLUID_OUNCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TABLESPOON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TABLESPOON');

  double get GSL_CONST_CGSM_TABLESPOON => _GSL_CONST_CGSM_TABLESPOON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TEASPOON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TEASPOON');

  double get GSL_CONST_CGSM_TEASPOON => _GSL_CONST_CGSM_TEASPOON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_CANADIAN_GALLON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_CANADIAN_GALLON');

  double get GSL_CONST_CGSM_CANADIAN_GALLON =>
      _GSL_CONST_CGSM_CANADIAN_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_UK_GALLON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_UK_GALLON');

  double get GSL_CONST_CGSM_UK_GALLON => _GSL_CONST_CGSM_UK_GALLON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_MILES_PER_HOUR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_MILES_PER_HOUR');

  double get GSL_CONST_CGSM_MILES_PER_HOUR =>
      _GSL_CONST_CGSM_MILES_PER_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_KILOMETERS_PER_HOUR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_KILOMETERS_PER_HOUR');

  double get GSL_CONST_CGSM_KILOMETERS_PER_HOUR =>
      _GSL_CONST_CGSM_KILOMETERS_PER_HOUR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_KNOT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_KNOT');

  double get GSL_CONST_CGSM_KNOT => _GSL_CONST_CGSM_KNOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_POUND_MASS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_POUND_MASS');

  double get GSL_CONST_CGSM_POUND_MASS => _GSL_CONST_CGSM_POUND_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_OUNCE_MASS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_OUNCE_MASS');

  double get GSL_CONST_CGSM_OUNCE_MASS => _GSL_CONST_CGSM_OUNCE_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TON');

  double get GSL_CONST_CGSM_TON => _GSL_CONST_CGSM_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_METRIC_TON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_METRIC_TON');

  double get GSL_CONST_CGSM_METRIC_TON => _GSL_CONST_CGSM_METRIC_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_UK_TON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_UK_TON');

  double get GSL_CONST_CGSM_UK_TON => _GSL_CONST_CGSM_UK_TON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TROY_OUNCE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TROY_OUNCE');

  double get GSL_CONST_CGSM_TROY_OUNCE => _GSL_CONST_CGSM_TROY_OUNCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_CARAT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_CARAT');

  double get GSL_CONST_CGSM_CARAT => _GSL_CONST_CGSM_CARAT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_UNIFIED_ATOMIC_MASS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_UNIFIED_ATOMIC_MASS');

  double get GSL_CONST_CGSM_UNIFIED_ATOMIC_MASS =>
      _GSL_CONST_CGSM_UNIFIED_ATOMIC_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_GRAM_FORCE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_GRAM_FORCE');

  double get GSL_CONST_CGSM_GRAM_FORCE => _GSL_CONST_CGSM_GRAM_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_POUND_FORCE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_POUND_FORCE');

  double get GSL_CONST_CGSM_POUND_FORCE => _GSL_CONST_CGSM_POUND_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_KILOPOUND_FORCE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_KILOPOUND_FORCE');

  double get GSL_CONST_CGSM_KILOPOUND_FORCE =>
      _GSL_CONST_CGSM_KILOPOUND_FORCE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_POUNDAL =
      _lookup<ffi.Double>('GSL_CONST_CGSM_POUNDAL');

  double get GSL_CONST_CGSM_POUNDAL => _GSL_CONST_CGSM_POUNDAL.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_CALORIE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_CALORIE');

  double get GSL_CONST_CGSM_CALORIE => _GSL_CONST_CGSM_CALORIE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BTU =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BTU');

  double get GSL_CONST_CGSM_BTU => _GSL_CONST_CGSM_BTU.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_THERM =
      _lookup<ffi.Double>('GSL_CONST_CGSM_THERM');

  double get GSL_CONST_CGSM_THERM => _GSL_CONST_CGSM_THERM.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_HORSEPOWER =
      _lookup<ffi.Double>('GSL_CONST_CGSM_HORSEPOWER');

  double get GSL_CONST_CGSM_HORSEPOWER => _GSL_CONST_CGSM_HORSEPOWER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BAR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BAR');

  double get GSL_CONST_CGSM_BAR => _GSL_CONST_CGSM_BAR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_STD_ATMOSPHERE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_STD_ATMOSPHERE');

  double get GSL_CONST_CGSM_STD_ATMOSPHERE =>
      _GSL_CONST_CGSM_STD_ATMOSPHERE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_TORR =
      _lookup<ffi.Double>('GSL_CONST_CGSM_TORR');

  double get GSL_CONST_CGSM_TORR => _GSL_CONST_CGSM_TORR.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_METER_OF_MERCURY =
      _lookup<ffi.Double>('GSL_CONST_CGSM_METER_OF_MERCURY');

  double get GSL_CONST_CGSM_METER_OF_MERCURY =>
      _GSL_CONST_CGSM_METER_OF_MERCURY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_INCH_OF_MERCURY =
      _lookup<ffi.Double>('GSL_CONST_CGSM_INCH_OF_MERCURY');

  double get GSL_CONST_CGSM_INCH_OF_MERCURY =>
      _GSL_CONST_CGSM_INCH_OF_MERCURY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_INCH_OF_WATER =
      _lookup<ffi.Double>('GSL_CONST_CGSM_INCH_OF_WATER');

  double get GSL_CONST_CGSM_INCH_OF_WATER =>
      _GSL_CONST_CGSM_INCH_OF_WATER.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PSI =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PSI');

  double get GSL_CONST_CGSM_PSI => _GSL_CONST_CGSM_PSI.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_POISE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_POISE');

  double get GSL_CONST_CGSM_POISE => _GSL_CONST_CGSM_POISE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_STOKES =
      _lookup<ffi.Double>('GSL_CONST_CGSM_STOKES');

  double get GSL_CONST_CGSM_STOKES => _GSL_CONST_CGSM_STOKES.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_STILB =
      _lookup<ffi.Double>('GSL_CONST_CGSM_STILB');

  double get GSL_CONST_CGSM_STILB => _GSL_CONST_CGSM_STILB.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_LUMEN =
      _lookup<ffi.Double>('GSL_CONST_CGSM_LUMEN');

  double get GSL_CONST_CGSM_LUMEN => _GSL_CONST_CGSM_LUMEN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_LUX =
      _lookup<ffi.Double>('GSL_CONST_CGSM_LUX');

  double get GSL_CONST_CGSM_LUX => _GSL_CONST_CGSM_LUX.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PHOT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PHOT');

  double get GSL_CONST_CGSM_PHOT => _GSL_CONST_CGSM_PHOT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FOOTCANDLE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FOOTCANDLE');

  double get GSL_CONST_CGSM_FOOTCANDLE => _GSL_CONST_CGSM_FOOTCANDLE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_LAMBERT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_LAMBERT');

  double get GSL_CONST_CGSM_LAMBERT => _GSL_CONST_CGSM_LAMBERT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FOOTLAMBERT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FOOTLAMBERT');

  double get GSL_CONST_CGSM_FOOTLAMBERT => _GSL_CONST_CGSM_FOOTLAMBERT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_CURIE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_CURIE');

  double get GSL_CONST_CGSM_CURIE => _GSL_CONST_CGSM_CURIE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ROENTGEN =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ROENTGEN');

  double get GSL_CONST_CGSM_ROENTGEN => _GSL_CONST_CGSM_ROENTGEN.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_RAD =
      _lookup<ffi.Double>('GSL_CONST_CGSM_RAD');

  double get GSL_CONST_CGSM_RAD => _GSL_CONST_CGSM_RAD.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_SOLAR_MASS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_SOLAR_MASS');

  double get GSL_CONST_CGSM_SOLAR_MASS => _GSL_CONST_CGSM_SOLAR_MASS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BOHR_RADIUS =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BOHR_RADIUS');

  double get GSL_CONST_CGSM_BOHR_RADIUS => _GSL_CONST_CGSM_BOHR_RADIUS.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_NEWTON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_NEWTON');

  double get GSL_CONST_CGSM_NEWTON => _GSL_CONST_CGSM_NEWTON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_DYNE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_DYNE');

  double get GSL_CONST_CGSM_DYNE => _GSL_CONST_CGSM_DYNE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_JOULE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_JOULE');

  double get GSL_CONST_CGSM_JOULE => _GSL_CONST_CGSM_JOULE.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ERG =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ERG');

  double get GSL_CONST_CGSM_ERG => _GSL_CONST_CGSM_ERG.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_BOHR_MAGNETON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_BOHR_MAGNETON');

  double get GSL_CONST_CGSM_BOHR_MAGNETON =>
      _GSL_CONST_CGSM_BOHR_MAGNETON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_NUCLEAR_MAGNETON =
      _lookup<ffi.Double>('GSL_CONST_CGSM_NUCLEAR_MAGNETON');

  double get GSL_CONST_CGSM_NUCLEAR_MAGNETON =>
      _GSL_CONST_CGSM_NUCLEAR_MAGNETON.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ELECTRON_MAGNETIC_MOMENT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ELECTRON_MAGNETIC_MOMENT');

  double get GSL_CONST_CGSM_ELECTRON_MAGNETIC_MOMENT =>
      _GSL_CONST_CGSM_ELECTRON_MAGNETIC_MOMENT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_PROTON_MAGNETIC_MOMENT =
      _lookup<ffi.Double>('GSL_CONST_CGSM_PROTON_MAGNETIC_MOMENT');

  double get GSL_CONST_CGSM_PROTON_MAGNETIC_MOMENT =>
      _GSL_CONST_CGSM_PROTON_MAGNETIC_MOMENT.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_FARADAY =
      _lookup<ffi.Double>('GSL_CONST_CGSM_FARADAY');

  double get GSL_CONST_CGSM_FARADAY => _GSL_CONST_CGSM_FARADAY.value;

  late final ffi.Pointer<ffi.Double> _GSL_CONST_CGSM_ELECTRON_CHARGE =
      _lookup<ffi.Double>('GSL_CONST_CGSM_ELECTRON_CHARGE');

  double get GSL_CONST_CGSM_ELECTRON_CHARGE =>
      _GSL_CONST_CGSM_ELECTRON_CHARGE.value;

  late final ffi.Pointer<ffi.Double> _M_E = _lookup<ffi.Double>('M_E');

  double get M_E => _M_E.value;

  late final ffi.Pointer<ffi.Double> _M_LOG2E = _lookup<ffi.Double>('M_LOG2E');

  double get M_LOG2E => _M_LOG2E.value;

  late final ffi.Pointer<ffi.Double> _M_LOG10E =
      _lookup<ffi.Double>('M_LOG10E');

  double get M_LOG10E => _M_LOG10E.value;

  late final ffi.Pointer<ffi.Double> _M_SQRT2 = _lookup<ffi.Double>('M_SQRT2');

  double get M_SQRT2 => _M_SQRT2.value;

  late final ffi.Pointer<ffi.Double> _M_SQRT1_2 =
      _lookup<ffi.Double>('M_SQRT1_2');

  double get M_SQRT1_2 => _M_SQRT1_2.value;

  late final ffi.Pointer<ffi.Double> _M_SQRT3 = _lookup<ffi.Double>('M_SQRT3');

  double get M_SQRT3 => _M_SQRT3.value;

  late final ffi.Pointer<ffi.Double> _M_PI = _lookup<ffi.Double>('M_PI');

  double get M_PI => _M_PI.value;

  late final ffi.Pointer<ffi.Double> _M_PI_2 = _lookup<ffi.Double>('M_PI_2');

  double get M_PI_2 => _M_PI_2.value;

  late final ffi.Pointer<ffi.Double> _M_PI_4 = _lookup<ffi.Double>('M_PI_4');

  double get M_PI_4 => _M_PI_4.value;

  late final ffi.Pointer<ffi.Double> _M_SQRTPI =
      _lookup<ffi.Double>('M_SQRTPI');

  double get M_SQRTPI => _M_SQRTPI.value;

  late final ffi.Pointer<ffi.Double> _M_2_SQRTPI =
      _lookup<ffi.Double>('M_2_SQRTPI');

  double get M_2_SQRTPI => _M_2_SQRTPI.value;

  late final ffi.Pointer<ffi.Double> _M_1_PI = _lookup<ffi.Double>('M_1_PI');

  double get M_1_PI => _M_1_PI.value;

  late final ffi.Pointer<ffi.Double> _M_2_PI = _lookup<ffi.Double>('M_2_PI');

  double get M_2_PI => _M_2_PI.value;

  late final ffi.Pointer<ffi.Double> _M_LN10 = _lookup<ffi.Double>('M_LN10');

  double get M_LN10 => _M_LN10.value;

  late final ffi.Pointer<ffi.Double> _M_LN2 = _lookup<ffi.Double>('M_LN2');

  double get M_LN2 => _M_LN2.value;

  late final ffi.Pointer<ffi.Double> _M_LNPI = _lookup<ffi.Double>('M_LNPI');

  double get M_LNPI => _M_LNPI.value;

  late final ffi.Pointer<ffi.Double> _M_EULER = _lookup<ffi.Double>('M_EULER');

  double get M_EULER => _M_EULER.value;

  late final ffi.Pointer<ffi.Double> _GSL_IEEE_MODE =
      _lookup<ffi.Double>('GSL_IEEE_MODE');

  double get GSL_IEEE_MODE => _GSL_IEEE_MODE.value;

  late final ffi.Pointer<ffi.Double> _GSL_IMAG =
      _lookup<ffi.Double>('GSL_IMAG');

  double get GSL_IMAG => _GSL_IMAG.value;

  late final ffi.Pointer<ffi.Double> _GSL_REAL =
      _lookup<ffi.Double>('GSL_REAL');

  double get GSL_REAL => _GSL_REAL.value;

  late final ffi.Pointer<ffi.Double> _GSL_NAN = _lookup<ffi.Double>('GSL_NAN');

  double get GSL_NAN => _GSL_NAN.value;

  late final ffi.Pointer<ffi.Double> _GSL_NEGINF =
      _lookup<ffi.Double>('GSL_NEGINF');

  double get GSL_NEGINF => _GSL_NEGINF.value;

  late final ffi.Pointer<ffi.Double> _GSL_POSINF =
      _lookup<ffi.Double>('GSL_POSINF');

  double get GSL_POSINF => _GSL_POSINF.value;

  late final ffi.Pointer<ffi.Double> _GSL_ERROR_VAL =
      _lookup<ffi.Double>('GSL_ERROR_VAL');

  double get GSL_ERROR_VAL => _GSL_ERROR_VAL.value;

  late final ffi.Pointer<ffi.Double> _GSL_ERROR =
      _lookup<ffi.Double>('GSL_ERROR');

  double get GSL_ERROR => _GSL_ERROR.value;

  late final ffi.Pointer<ffi.Double> _GSL_RNG_SEED =
      _lookup<ffi.Double>('GSL_RNG_SEED');

  double get GSL_RNG_SEED => _GSL_RNG_SEED.value;

  late final ffi.Pointer<ffi.Double> _GSL_RNG_TYPE =
      _lookup<ffi.Double>('GSL_RNG_TYPE');

  double get GSL_RNG_TYPE => _GSL_RNG_TYPE.value;

  late final ffi.Pointer<ffi.Double> _GSL_RANGE_CHECK_OFF =
      _lookup<ffi.Double>('GSL_RANGE_CHECK_OFF');

  double get GSL_RANGE_CHECK_OFF => _GSL_RANGE_CHECK_OFF.value;

  late final ffi.Pointer<ffi.Double> _GSL_SET_COMPLEX =
      _lookup<ffi.Double>('GSL_SET_COMPLEX');

  double get GSL_SET_COMPLEX => _GSL_SET_COMPLEX.value;

  late final ffi.Pointer<ffi.Double> _GSL_SIGN =
      _lookup<ffi.Double>('GSL_SIGN');

  double get GSL_SIGN => _GSL_SIGN.value;

  double gsl_bessel_j0(
    double x,
  ) {
    return _gsl_bessel_j0(
      x,
    );
  }

  late final _gsl_bessel_j0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_bessel_j0');
  late final _gsl_bessel_j0 =
      _gsl_bessel_j0Ptr.asFunction<double Function(double)>();

  double gsl_bessel_j1(
    double x,
  ) {
    return _gsl_bessel_j1(
      x,
    );
  }

  late final _gsl_bessel_j1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_bessel_j1');
  late final _gsl_bessel_j1 =
      _gsl_bessel_j1Ptr.asFunction<double Function(double)>();

  double gsl_bessel_y0(
    double x,
  ) {
    return _gsl_bessel_y0(
      x,
    );
  }

  late final _gsl_bessel_y0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_bessel_y0');
  late final _gsl_bessel_y0 =
      _gsl_bessel_y0Ptr.asFunction<double Function(double)>();

  double gsl_bessel_y1(
    double x,
  ) {
    return _gsl_bessel_y1(
      x,
    );
  }

  late final _gsl_bessel_y1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_bessel_y1');
  late final _gsl_bessel_y1 =
      _gsl_bessel_y1Ptr.asFunction<double Function(double)>();

  double gsl_sf_sin(
    double x,
  ) {
    return _gsl_sf_sin(
      x,
    );
  }

  late final _gsl_sf_sinPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_sin');
  late final _gsl_sf_sin = _gsl_sf_sinPtr.asFunction<double Function(double)>();

  double gsl_sf_cos(
    double x,
  ) {
    return _gsl_sf_cos(
      x,
    );
  }

  late final _gsl_sf_cosPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_cos');
  late final _gsl_sf_cos = _gsl_sf_cosPtr.asFunction<double Function(double)>();

  double gsl_sf_tan(
    double x,
  ) {
    return _gsl_sf_tan(
      x,
    );
  }

  late final _gsl_sf_tanPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_tan');
  late final _gsl_sf_tan = _gsl_sf_tanPtr.asFunction<double Function(double)>();

  double gsl_sf_sec(
    double x,
  ) {
    return _gsl_sf_sec(
      x,
    );
  }

  late final _gsl_sf_secPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_sec');
  late final _gsl_sf_sec = _gsl_sf_secPtr.asFunction<double Function(double)>();

  double gsl_sf_csc(
    double x,
  ) {
    return _gsl_sf_csc(
      x,
    );
  }

  late final _gsl_sf_cscPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_csc');
  late final _gsl_sf_csc = _gsl_sf_cscPtr.asFunction<double Function(double)>();

  double gsl_sf_cot(
    double x,
  ) {
    return _gsl_sf_cot(
      x,
    );
  }

  late final _gsl_sf_cotPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_cot');
  late final _gsl_sf_cot = _gsl_sf_cotPtr.asFunction<double Function(double)>();

  double gsl_sf_asin(
    double x,
  ) {
    return _gsl_sf_asin(
      x,
    );
  }

  late final _gsl_sf_asinPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_asin');
  late final _gsl_sf_asin =
      _gsl_sf_asinPtr.asFunction<double Function(double)>();

  double gsl_sf_acos(
    double x,
  ) {
    return _gsl_sf_acos(
      x,
    );
  }

  late final _gsl_sf_acosPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_acos');
  late final _gsl_sf_acos =
      _gsl_sf_acosPtr.asFunction<double Function(double)>();

  double gsl_sf_atan(
    double x,
  ) {
    return _gsl_sf_atan(
      x,
    );
  }

  late final _gsl_sf_atanPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_atan');
  late final _gsl_sf_atan =
      _gsl_sf_atanPtr.asFunction<double Function(double)>();

  double gsl_sf_acosh(
    double x,
  ) {
    return _gsl_sf_acosh(
      x,
    );
  }

  late final _gsl_sf_acoshPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_acosh');
  late final _gsl_sf_acosh =
      _gsl_sf_acoshPtr.asFunction<double Function(double)>();

  double gsl_sf_asinh(
    double x,
  ) {
    return _gsl_sf_asinh(
      x,
    );
  }

  late final _gsl_sf_asinhPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_asinh');
  late final _gsl_sf_asinh =
      _gsl_sf_asinhPtr.asFunction<double Function(double)>();

  double gsl_sf_atanh(
    double x,
  ) {
    return _gsl_sf_atanh(
      x,
    );
  }

  late final _gsl_sf_atanhPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_atanh');
  late final _gsl_sf_atanh =
      _gsl_sf_atanhPtr.asFunction<double Function(double)>();

  double gsl_sf_sinh(
    double x,
  ) {
    return _gsl_sf_sinh(
      x,
    );
  }

  late final _gsl_sf_sinhPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_sinh');
  late final _gsl_sf_sinh =
      _gsl_sf_sinhPtr.asFunction<double Function(double)>();

  double gsl_sf_cosh(
    double x,
  ) {
    return _gsl_sf_cosh(
      x,
    );
  }

  late final _gsl_sf_coshPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_cosh');
  late final _gsl_sf_cosh =
      _gsl_sf_coshPtr.asFunction<double Function(double)>();

  double gsl_sf_tanh(
    double x,
  ) {
    return _gsl_sf_tanh(
      x,
    );
  }

  late final _gsl_sf_tanhPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_tanh');
  late final _gsl_sf_tanh =
      _gsl_sf_tanhPtr.asFunction<double Function(double)>();

  double gsl_sf_sech(
    double x,
  ) {
    return _gsl_sf_sech(
      x,
    );
  }

  late final _gsl_sf_sechPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_sech');
  late final _gsl_sf_sech =
      _gsl_sf_sechPtr.asFunction<double Function(double)>();

  double gsl_sf_csch(
    double x,
  ) {
    return _gsl_sf_csch(
      x,
    );
  }

  late final _gsl_sf_cschPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_csch');
  late final _gsl_sf_csch =
      _gsl_sf_cschPtr.asFunction<double Function(double)>();

  double gsl_sf_coth(
    double x,
  ) {
    return _gsl_sf_coth(
      x,
    );
  }

  late final _gsl_sf_cothPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_coth');
  late final _gsl_sf_coth =
      _gsl_sf_cothPtr.asFunction<double Function(double)>();

  double gsl_sf_ellint_Kcomp(
    double k,
  ) {
    return _gsl_sf_ellint_Kcomp(
      k,
    );
  }

  late final _gsl_sf_ellint_KcompPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_ellint_Kcomp');
  late final _gsl_sf_ellint_Kcomp =
      _gsl_sf_ellint_KcompPtr.asFunction<double Function(double)>();

  double gsl_sf_ellint_Ecomp(
    double k,
  ) {
    return _gsl_sf_ellint_Ecomp(
      k,
    );
  }

  late final _gsl_sf_ellint_EcompPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_ellint_Ecomp');
  late final _gsl_sf_ellint_Ecomp =
      _gsl_sf_ellint_EcompPtr.asFunction<double Function(double)>();

  double gsl_sf_ellint_Pcomp(
    double k,
    double n,
  ) {
    return _gsl_sf_ellint_Pcomp(
      k,
      n,
    );
  }

  late final _gsl_sf_ellint_PcompPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_ellint_Pcomp');
  late final _gsl_sf_ellint_Pcomp =
      _gsl_sf_ellint_PcompPtr.asFunction<double Function(double, double)>();

  double gsl_sf_ellint_Dcomp(
    double k,
    double n,
  ) {
    return _gsl_sf_ellint_Dcomp(
      k,
      n,
    );
  }

  late final _gsl_sf_ellint_DcompPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_ellint_Dcomp');
  late final _gsl_sf_ellint_Dcomp =
      _gsl_sf_ellint_DcompPtr.asFunction<double Function(double, double)>();

  double gsl_sf_airy_Ai(
    double x,
  ) {
    return _gsl_sf_airy_Ai(
      x,
    );
  }

  late final _gsl_sf_airy_AiPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Ai');
  late final _gsl_sf_airy_Ai =
      _gsl_sf_airy_AiPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Bi(
    double x,
  ) {
    return _gsl_sf_airy_Bi(
      x,
    );
  }

  late final _gsl_sf_airy_BiPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Bi');
  late final _gsl_sf_airy_Bi =
      _gsl_sf_airy_BiPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Ai_scaled(
    double x,
  ) {
    return _gsl_sf_airy_Ai_scaled(
      x,
    );
  }

  late final _gsl_sf_airy_Ai_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Ai_scaled');
  late final _gsl_sf_airy_Ai_scaled =
      _gsl_sf_airy_Ai_scaledPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Bi_scaled(
    double x,
  ) {
    return _gsl_sf_airy_Bi_scaled(
      x,
    );
  }

  late final _gsl_sf_airy_Bi_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Bi_scaled');
  late final _gsl_sf_airy_Bi_scaled =
      _gsl_sf_airy_Bi_scaledPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Ai_deriv(
    double x,
  ) {
    return _gsl_sf_airy_Ai_deriv(
      x,
    );
  }

  late final _gsl_sf_airy_Ai_derivPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Ai_deriv');
  late final _gsl_sf_airy_Ai_deriv =
      _gsl_sf_airy_Ai_derivPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Bi_deriv(
    double x,
  ) {
    return _gsl_sf_airy_Bi_deriv(
      x,
    );
  }

  late final _gsl_sf_airy_Bi_derivPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Bi_deriv');
  late final _gsl_sf_airy_Bi_deriv =
      _gsl_sf_airy_Bi_derivPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Ai_deriv_scaled(
    double x,
  ) {
    return _gsl_sf_airy_Ai_deriv_scaled(
      x,
    );
  }

  late final _gsl_sf_airy_Ai_deriv_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Ai_deriv_scaled');
  late final _gsl_sf_airy_Ai_deriv_scaled =
      _gsl_sf_airy_Ai_deriv_scaledPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_Bi_deriv_scaled(
    double x,
  ) {
    return _gsl_sf_airy_Bi_deriv_scaled(
      x,
    );
  }

  late final _gsl_sf_airy_Bi_deriv_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_airy_Bi_deriv_scaled');
  late final _gsl_sf_airy_Bi_deriv_scaled =
      _gsl_sf_airy_Bi_deriv_scaledPtr.asFunction<double Function(double)>();

  double gsl_sf_airy_zero_Ai(
    int n,
  ) {
    return _gsl_sf_airy_zero_Ai(
      n,
    );
  }

  late final _gsl_sf_airy_zero_AiPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Ai');
  late final _gsl_sf_airy_zero_Ai =
      _gsl_sf_airy_zero_AiPtr.asFunction<double Function(int)>();

  double gsl_sf_airy_zero_Bi(
    int n,
  ) {
    return _gsl_sf_airy_zero_Bi(
      n,
    );
  }

  late final _gsl_sf_airy_zero_BiPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Bi');
  late final _gsl_sf_airy_zero_Bi =
      _gsl_sf_airy_zero_BiPtr.asFunction<double Function(int)>();

  double gsl_sf_airy_zero_Ai_deriv(
    int n,
  ) {
    return _gsl_sf_airy_zero_Ai_deriv(
      n,
    );
  }

  late final _gsl_sf_airy_zero_Ai_derivPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Ai_deriv');
  late final _gsl_sf_airy_zero_Ai_deriv =
      _gsl_sf_airy_zero_Ai_derivPtr.asFunction<double Function(int)>();

  double gsl_sf_airy_zero_Bi_deriv(
    int n,
  ) {
    return _gsl_sf_airy_zero_Bi_deriv(
      n,
    );
  }

  late final _gsl_sf_airy_zero_Bi_derivPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Bi_deriv');
  late final _gsl_sf_airy_zero_Bi_deriv =
      _gsl_sf_airy_zero_Bi_derivPtr.asFunction<double Function(int)>();

  double gsl_sf_airy_zero_Ai_deriv_scaled(
    int n,
  ) {
    return _gsl_sf_airy_zero_Ai_deriv_scaled(
      n,
    );
  }

  late final _gsl_sf_airy_zero_Ai_deriv_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Ai_deriv_scaled');
  late final _gsl_sf_airy_zero_Ai_deriv_scaled =
      _gsl_sf_airy_zero_Ai_deriv_scaledPtr.asFunction<double Function(int)>();

  double gsl_sf_airy_zero_Bi_deriv_scaled(
    int n,
  ) {
    return _gsl_sf_airy_zero_Bi_deriv_scaled(
      n,
    );
  }

  late final _gsl_sf_airy_zero_Bi_deriv_scaledPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.UnsignedInt)>>(
          'gsl_sf_airy_zero_Bi_deriv_scaled');
  late final _gsl_sf_airy_zero_Bi_deriv_scaled =
      _gsl_sf_airy_zero_Bi_deriv_scaledPtr.asFunction<double Function(int)>();

  double gsl_sf_bessel_J0(
    double x,
  ) {
    return _gsl_sf_bessel_J0(
      x,
    );
  }

  late final _gsl_sf_bessel_J0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_bessel_J0');
  late final _gsl_sf_bessel_J0 =
      _gsl_sf_bessel_J0Ptr.asFunction<double Function(double)>();

  double gsl_sf_bessel_J1(
    double x,
  ) {
    return _gsl_sf_bessel_J1(
      x,
    );
  }

  late final _gsl_sf_bessel_J1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_bessel_J1');
  late final _gsl_sf_bessel_J1 =
      _gsl_sf_bessel_J1Ptr.asFunction<double Function(double)>();

  double gsl_sf_bessel_Y0(
    double x,
  ) {
    return _gsl_sf_bessel_Y0(
      x,
    );
  }

  late final _gsl_sf_bessel_Y0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_bessel_Y0');
  late final _gsl_sf_bessel_Y0 =
      _gsl_sf_bessel_Y0Ptr.asFunction<double Function(double)>();

  double gsl_sf_bessel_Y1(
    double x,
  ) {
    return _gsl_sf_bessel_Y1(
      x,
    );
  }

  late final _gsl_sf_bessel_Y1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_bessel_Y1');
  late final _gsl_sf_bessel_Y1 =
      _gsl_sf_bessel_Y1Ptr.asFunction<double Function(double)>();

  double gsl_sf_legendre_Plm(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_Plm(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_PlmPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(
              ffi.Double, ffi.Double, ffi.Double)>>('gsl_sf_legendre_Plm');
  late final _gsl_sf_legendre_Plm = _gsl_sf_legendre_PlmPtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_sphPlm(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_sphPlm(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_sphPlmPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(
              ffi.Double, ffi.Double, ffi.Double)>>('gsl_sf_legendre_sphPlm');
  late final _gsl_sf_legendre_sphPlm = _gsl_sf_legendre_sphPlmPtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_Plm_deriv(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_Plm_deriv(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_Plm_derivPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double,
              ffi.Double)>>('gsl_sf_legendre_Plm_deriv');
  late final _gsl_sf_legendre_Plm_deriv = _gsl_sf_legendre_Plm_derivPtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_sphPlm_deriv(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_sphPlm_deriv(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_sphPlm_derivPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double,
              ffi.Double)>>('gsl_sf_legendre_sphPlm_deriv');
  late final _gsl_sf_legendre_sphPlm_deriv = _gsl_sf_legendre_sphPlm_derivPtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_chebyshev_T0(
    double x,
  ) {
    return _gsl_sf_chebyshev_T0(
      x,
    );
  }

  late final _gsl_sf_chebyshev_T0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_chebyshev_T0');
  late final _gsl_sf_chebyshev_T0 =
      _gsl_sf_chebyshev_T0Ptr.asFunction<double Function(double)>();

  double gsl_sf_chebyshev_T1(
    double x,
  ) {
    return _gsl_sf_chebyshev_T1(
      x,
    );
  }

  late final _gsl_sf_chebyshev_T1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_chebyshev_T1');
  late final _gsl_sf_chebyshev_T1 =
      _gsl_sf_chebyshev_T1Ptr.asFunction<double Function(double)>();

  double gsl_sf_chebyshev_Tn(
    int n,
    double x,
  ) {
    return _gsl_sf_chebyshev_Tn(
      n,
      x,
    );
  }

  late final _gsl_sf_chebyshev_TnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_chebyshev_Tn');
  late final _gsl_sf_chebyshev_Tn =
      _gsl_sf_chebyshev_TnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_chebyshev_U0(
    double x,
  ) {
    return _gsl_sf_chebyshev_U0(
      x,
    );
  }

  late final _gsl_sf_chebyshev_U0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_chebyshev_U0');
  late final _gsl_sf_chebyshev_U0 =
      _gsl_sf_chebyshev_U0Ptr.asFunction<double Function(double)>();

  double gsl_sf_chebyshev_U1(
    double x,
  ) {
    return _gsl_sf_chebyshev_U1(
      x,
    );
  }

  late final _gsl_sf_chebyshev_U1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_chebyshev_U1');
  late final _gsl_sf_chebyshev_U1 =
      _gsl_sf_chebyshev_U1Ptr.asFunction<double Function(double)>();

  double gsl_sf_chebyshev_Un(
    int n,
    double x,
  ) {
    return _gsl_sf_chebyshev_Un(
      n,
      x,
    );
  }

  late final _gsl_sf_chebyshev_UnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_chebyshev_Un');
  late final _gsl_sf_chebyshev_Un =
      _gsl_sf_chebyshev_UnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_chebyshev_Vn(
    int n,
    double x,
  ) {
    return _gsl_sf_chebyshev_Vn(
      n,
      x,
    );
  }

  late final _gsl_sf_chebyshev_VnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_chebyshev_Vn');
  late final _gsl_sf_chebyshev_Vn =
      _gsl_sf_chebyshev_VnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_hankel_H0(
    double x,
  ) {
    return _gsl_sf_hankel_H0(
      x,
    );
  }

  late final _gsl_sf_hankel_H0Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_hankel_H0');
  late final _gsl_sf_hankel_H0 =
      _gsl_sf_hankel_H0Ptr.asFunction<double Function(double)>();

  double gsl_sf_hankel_H1(
    double x,
  ) {
    return _gsl_sf_hankel_H1(
      x,
    );
  }

  late final _gsl_sf_hankel_H1Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_hankel_H1');
  late final _gsl_sf_hankel_H1 =
      _gsl_sf_hankel_H1Ptr.asFunction<double Function(double)>();

  double gsl_sf_hankel_H2(
    double x,
  ) {
    return _gsl_sf_hankel_H2(
      x,
    );
  }

  late final _gsl_sf_hankel_H2Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_hankel_H2');
  late final _gsl_sf_hankel_H2 =
      _gsl_sf_hankel_H2Ptr.asFunction<double Function(double)>();

  double gsl_sf_hankel_H3(
    double x,
  ) {
    return _gsl_sf_hankel_H3(
      x,
    );
  }

  late final _gsl_sf_hankel_H3Ptr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_hankel_H3');
  late final _gsl_sf_hankel_H3 =
      _gsl_sf_hankel_H3Ptr.asFunction<double Function(double)>();

  double gsl_sf_legendre_Plm_e(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_Plm_e(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_Plm_ePtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(
              ffi.Double, ffi.Double, ffi.Double)>>('gsl_sf_legendre_Plm_e');
  late final _gsl_sf_legendre_Plm_e = _gsl_sf_legendre_Plm_ePtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_Plm_deriv_e(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_Plm_deriv_e(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_Plm_deriv_ePtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double,
              ffi.Double)>>('gsl_sf_legendre_Plm_deriv_e');
  late final _gsl_sf_legendre_Plm_deriv_e = _gsl_sf_legendre_Plm_deriv_ePtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_sphPlm_e(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_sphPlm_e(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_sphPlm_ePtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(
              ffi.Double, ffi.Double, ffi.Double)>>('gsl_sf_legendre_sphPlm_e');
  late final _gsl_sf_legendre_sphPlm_e = _gsl_sf_legendre_sphPlm_ePtr
      .asFunction<double Function(double, double, double)>();

  double gsl_sf_legendre_sphPlm_deriv_e(
    double l,
    double m,
    double x,
  ) {
    return _gsl_sf_legendre_sphPlm_deriv_e(
      l,
      m,
      x,
    );
  }

  late final _gsl_sf_legendre_sphPlm_deriv_ePtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Double, ffi.Double,
              ffi.Double)>>('gsl_sf_legendre_sphPlm_deriv_e');
  late final _gsl_sf_legendre_sphPlm_deriv_e =
      _gsl_sf_legendre_sphPlm_deriv_ePtr
          .asFunction<double Function(double, double, double)>();

  double gsl_sf_bessel_Jn(
    int n,
    double x,
  ) {
    return _gsl_sf_bessel_Jn(
      n,
      x,
    );
  }

  late final _gsl_sf_bessel_JnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_bessel_Jn');
  late final _gsl_sf_bessel_Jn =
      _gsl_sf_bessel_JnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_bessel_Yn(
    int n,
    double x,
  ) {
    return _gsl_sf_bessel_Yn(
      n,
      x,
    );
  }

  late final _gsl_sf_bessel_YnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_bessel_Yn');
  late final _gsl_sf_bessel_Yn =
      _gsl_sf_bessel_YnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_bessel_In(
    int n,
    double x,
  ) {
    return _gsl_sf_bessel_In(
      n,
      x,
    );
  }

  late final _gsl_sf_bessel_InPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_bessel_In');
  late final _gsl_sf_bessel_In =
      _gsl_sf_bessel_InPtr.asFunction<double Function(int, double)>();

  double gsl_sf_bessel_Kn(
    int n,
    double x,
  ) {
    return _gsl_sf_bessel_Kn(
      n,
      x,
    );
  }

  late final _gsl_sf_bessel_KnPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int, ffi.Double)>>(
          'gsl_sf_bessel_Kn');
  late final _gsl_sf_bessel_Kn =
      _gsl_sf_bessel_KnPtr.asFunction<double Function(int, double)>();

  double gsl_sf_legendre_Plm_e_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_Plm_e_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_Plm_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_Plm_e_array');
  late final _gsl_sf_legendre_Plm_e_array = _gsl_sf_legendre_Plm_e_arrayPtr
      .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_Plm_deriv_e_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_Plm_deriv_e_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_Plm_deriv_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_Plm_deriv_e_array');
  late final _gsl_sf_legendre_Plm_deriv_e_array =
      _gsl_sf_legendre_Plm_deriv_e_arrayPtr
          .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_sphPlm_e_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_sphPlm_e_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_sphPlm_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_sphPlm_e_array');
  late final _gsl_sf_legendre_sphPlm_e_array =
      _gsl_sf_legendre_sphPlm_e_arrayPtr
          .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_sphPlm_deriv_e_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_sphPlm_deriv_e_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_sphPlm_deriv_e_arrayPtr = _lookup<
          ffi.NativeFunction<
              ffi.Double Function(
                  ffi.Int, ffi.Double, ffi.Pointer<ffi.Double>)>>(
      'gsl_sf_legendre_sphPlm_deriv_e_array');
  late final _gsl_sf_legendre_sphPlm_deriv_e_array =
      _gsl_sf_legendre_sphPlm_deriv_e_arrayPtr
          .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Jnu(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Jnu(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_JnuPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Jnu');
  late final _gsl_sf_bessel_Jnu =
      _gsl_sf_bessel_JnuPtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Ynu(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Ynu(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_YnuPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Ynu');
  late final _gsl_sf_bessel_Ynu =
      _gsl_sf_bessel_YnuPtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Inu(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Inu(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_InuPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Inu');
  late final _gsl_sf_bessel_Inu =
      _gsl_sf_bessel_InuPtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Knu(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Knu(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_KnuPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Knu');
  late final _gsl_sf_bessel_Knu =
      _gsl_sf_bessel_KnuPtr.asFunction<double Function(double, double)>();

  double gsl_sf_exp(
    double x,
  ) {
    return _gsl_sf_exp(
      x,
    );
  }

  late final _gsl_sf_expPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_exp');
  late final _gsl_sf_exp = _gsl_sf_expPtr.asFunction<double Function(double)>();

  double gsl_sf_log(
    double x,
  ) {
    return _gsl_sf_log(
      x,
    );
  }

  late final _gsl_sf_logPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_log');
  late final _gsl_sf_log = _gsl_sf_logPtr.asFunction<double Function(double)>();

  double gsl_sf_gamma(
    double x,
  ) {
    return _gsl_sf_gamma(
      x,
    );
  }

  late final _gsl_sf_gammaPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_gamma');
  late final _gsl_sf_gamma =
      _gsl_sf_gammaPtr.asFunction<double Function(double)>();

  double gsl_sf_lngamma(
    double x,
  ) {
    return _gsl_sf_lngamma(
      x,
    );
  }

  late final _gsl_sf_lngammaPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_lngamma');
  late final _gsl_sf_lngamma =
      _gsl_sf_lngammaPtr.asFunction<double Function(double)>();

  double gsl_sf_erf(
    double x,
  ) {
    return _gsl_sf_erf(
      x,
    );
  }

  late final _gsl_sf_erfPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_erf');
  late final _gsl_sf_erf = _gsl_sf_erfPtr.asFunction<double Function(double)>();

  double gsl_sf_erfc(
    double x,
  ) {
    return _gsl_sf_erfc(
      x,
    );
  }

  late final _gsl_sf_erfcPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_erfc');
  late final _gsl_sf_erfc =
      _gsl_sf_erfcPtr.asFunction<double Function(double)>();

  double gsl_sf_hazard(
    double x,
  ) {
    return _gsl_sf_hazard(
      x,
    );
  }

  late final _gsl_sf_hazardPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_hazard');
  late final _gsl_sf_hazard =
      _gsl_sf_hazardPtr.asFunction<double Function(double)>();

  double gsl_sf_bessel_Jnu_e(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Jnu_e(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_Jnu_ePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Jnu_e');
  late final _gsl_sf_bessel_Jnu_e =
      _gsl_sf_bessel_Jnu_ePtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Ynu_e(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Ynu_e(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_Ynu_ePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Ynu_e');
  late final _gsl_sf_bessel_Ynu_e =
      _gsl_sf_bessel_Ynu_ePtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Inu_e(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Inu_e(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_Inu_ePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Inu_e');
  late final _gsl_sf_bessel_Inu_e =
      _gsl_sf_bessel_Inu_ePtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Knu_e(
    double nu,
    double x,
  ) {
    return _gsl_sf_bessel_Knu_e(
      nu,
      x,
    );
  }

  late final _gsl_sf_bessel_Knu_ePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
          'gsl_sf_bessel_Knu_e');
  late final _gsl_sf_bessel_Knu_e =
      _gsl_sf_bessel_Knu_ePtr.asFunction<double Function(double, double)>();

  double gsl_sf_bessel_Jnu_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Jnu_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Jnu_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Jnu_array');
  late final _gsl_sf_bessel_Jnu_array = _gsl_sf_bessel_Jnu_arrayPtr.asFunction<
      double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Ynu_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Ynu_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Ynu_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Ynu_array');
  late final _gsl_sf_bessel_Ynu_array = _gsl_sf_bessel_Ynu_arrayPtr.asFunction<
      double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Inu_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Inu_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Inu_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Inu_array');
  late final _gsl_sf_bessel_Inu_array = _gsl_sf_bessel_Inu_arrayPtr.asFunction<
      double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Knu_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Knu_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Knu_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Knu_array');
  late final _gsl_sf_bessel_Knu_array = _gsl_sf_bessel_Knu_arrayPtr.asFunction<
      double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Jnu_e_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Jnu_e_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Jnu_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Jnu_e_array');
  late final _gsl_sf_bessel_Jnu_e_array =
      _gsl_sf_bessel_Jnu_e_arrayPtr.asFunction<
          double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Ynu_e_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Ynu_e_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Ynu_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Ynu_e_array');
  late final _gsl_sf_bessel_Ynu_e_array =
      _gsl_sf_bessel_Ynu_e_arrayPtr.asFunction<
          double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Inu_e_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Inu_e_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Inu_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Inu_e_array');
  late final _gsl_sf_bessel_Inu_e_array =
      _gsl_sf_bessel_Inu_e_arrayPtr.asFunction<
          double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_bessel_Knu_e_array(
    int nmax,
    double nu,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_bessel_Knu_e_array(
      nmax,
      nu,
      x,
      result,
    );
  }

  late final _gsl_sf_bessel_Knu_e_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_bessel_Knu_e_array');
  late final _gsl_sf_bessel_Knu_e_array =
      _gsl_sf_bessel_Knu_e_arrayPtr.asFunction<
          double Function(int, double, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_Plm_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_Plm_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_Plm_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_Plm_array');
  late final _gsl_sf_legendre_Plm_array = _gsl_sf_legendre_Plm_arrayPtr
      .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_Plm_deriv_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_Plm_deriv_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_Plm_deriv_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_Plm_deriv_array');
  late final _gsl_sf_legendre_Plm_deriv_array =
      _gsl_sf_legendre_Plm_deriv_arrayPtr
          .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_sphPlm_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_sphPlm_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_sphPlm_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_sphPlm_array');
  late final _gsl_sf_legendre_sphPlm_array = _gsl_sf_legendre_sphPlm_arrayPtr
      .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_sf_legendre_sphPlm_deriv_array(
    int lmax,
    double x,
    ffi.Pointer<ffi.Double> result,
  ) {
    return _gsl_sf_legendre_sphPlm_deriv_array(
      lmax,
      x,
      result,
    );
  }

  late final _gsl_sf_legendre_sphPlm_deriv_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Int, ffi.Double,
              ffi.Pointer<ffi.Double>)>>('gsl_sf_legendre_sphPlm_deriv_array');
  late final _gsl_sf_legendre_sphPlm_deriv_array =
      _gsl_sf_legendre_sphPlm_deriv_arrayPtr
          .asFunction<double Function(int, double, ffi.Pointer<ffi.Double>)>();

  double gsl_error_handler(
    ffi.Pointer<ffi.Char> reason,
    ffi.Pointer<ffi.Char> file,
    int line,
    int gsl_errno,
  ) {
    return _gsl_error_handler(
      reason,
      file,
      line,
      gsl_errno,
    );
  }

  late final _gsl_error_handlerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Int, ffi.Int)>>('gsl_error_handler');
  late final _gsl_error_handler = _gsl_error_handlerPtr.asFunction<
      double Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int)>();

  double gsl_set_error_handler_off() {
    return _gsl_set_error_handler_off();
  }

  late final _gsl_set_error_handler_offPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function()>>(
          'gsl_set_error_handler_off');
  late final _gsl_set_error_handler_off =
      _gsl_set_error_handler_offPtr.asFunction<double Function()>();

  double gsl_set_error_handler_on() {
    return _gsl_set_error_handler_on();
  }

  late final _gsl_set_error_handler_onPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function()>>(
          'gsl_set_error_handler_on');
  late final _gsl_set_error_handler_on =
      _gsl_set_error_handler_onPtr.asFunction<double Function()>();

  double gsl_set_error_handler(
    ffi.Pointer<
            ffi.NativeFunction<
                ffi.Double Function(
                    ffi.Pointer<ffi.Char> reason,
                    ffi.Pointer<ffi.Char> file,
                    ffi.Int line,
                    ffi.Int gsl_errno)>>
        handler,
  ) {
    return _gsl_set_error_handler(
      handler,
    );
  }

  late final _gsl_set_error_handlerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Double Function(
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Double Function(
                          ffi.Pointer<ffi.Char> reason,
                          ffi.Pointer<ffi.Char> file,
                          ffi.Int line,
                          ffi.Int gsl_errno)>>)>>('gsl_set_error_handler');
  late final _gsl_set_error_handler = _gsl_set_error_handlerPtr.asFunction<
      double Function(
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Double Function(
                      ffi.Pointer<ffi.Char> reason,
                      ffi.Pointer<ffi.Char> file,
                      ffi.Int line,
                      ffi.Int gsl_errno)>>)>();
}
