// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for GSL
class flutter_gsl {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  flutter_gsl(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  flutter_gsl.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// / Trigonometric functions
  double gsl_sf_sin(
    double x,
  ) {
    return _gsl_sf_sin(
      x,
    );
  }

  late final _gsl_sf_sinPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double)>>(
          'gsl_sf_sin');
  late final _gsl_sf_sin = _gsl_sf_sinPtr.asFunction<double Function(double)>();
}
